# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='turn',
            field=models.CharField(default='w', max_length=1),
            preserve_default=False,
        ),
    ]
