# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_logic', '0003_chessgame_game_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='pawn_over',
            field=models.BooleanField(default=False),
        ),
    ]
