# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_logic', '0004_chessgame_pawn_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='black_king_moved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='black_tower_left_moved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='black_tower_right_moved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='white_king_moved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='white_tower_left_moved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='white_tower_right_moved',
            field=models.BooleanField(default=False),
        ),
    ]
