# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_logic', '0006_auto_20160503_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chessgame',
            old_name='player1_pk',
            new_name='player_black_pk',
        ),
        migrations.RenameField(
            model_name='chessgame',
            old_name='player2_pk',
            new_name='player_white_pk',
        ),
    ]
