# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_logic', '0010_auto_20160616_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chess_logic.Room'),
        ),
    ]
