# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessuser',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
