# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160503_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=10)),
                ('player2', models.CharField(max_length=10)),
            ],
        ),
    ]
