# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenger', to='home.ChessUser'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='home.ChessUser'),
        ),
    ]
